### ISSUE TITLE
Проблема установки

### ISSUE THREAD

**Issue by kmolchanov** [yupe/yupe#2211]
При установке через композер следующей командой
```
composer create-project yupe/yupe:dev-dev runjoy/ --no-dev --prefer-dist
```
Во время установки модулей возникает ошибка:
```
Купоны: Во время установки возникла ошибка: Применяем миграцию m150414_124659_add_order_coupon_table > create table {{store_order_coupon}} ... done (time: 0.018s)
> add foreign key fk_{{store_order_coupon}}_order: {{store_order_coupon}} (order_id) references {{store_order}} (id) ...Exception: CDbCommand не удалось исполнить SQL-запрос: SQLSTATE[HY000]: General error: 1005 Can't create table 'runjoy.#sql-464_c3' (errno: 150). The SQL statement executed was: ALTER TABLE `yupe_store_order_coupon` ADD CONSTRAINT `fk_yupe_store_order_coupon_order` FOREIGN KEY (`order_id`) REFERENCES `yupe_store_order` (`id`) ON DELETE CASCADE (/home/kmolchanov/web/runjoy/vendor/yiisoft/yii/framework/db/CDbCommand.php:358) #0 /home/kmolchanov/web/runjoy/vendor/yiisoft/yii/framework/db/CDbCommand.php(1463): CDbCommand->execute() #1 /home/kmolchanov/web/runjoy/vendor/yiisoft/yii/framework/db/CDbMigration.php(366): CDbCommand->addForeignKey('fk_{{store_orde...', '{{store_order_c...', 'order_id', '{{store_order}}', 'id', 'CASCADE', NULL) #2 /home/kmolchanov/web/runjoy/protected/modules/coupon/install/migrations/m150414_124659_add_order_coupon_table.php(15): CDbMigration->addForeignKey('fk_{{store_orde...', '{{store_order_c...', 'order_id', '{{store_order}}', 'id', 'CASCADE') #3 /home/kmolchanov/web/runjoy/vendor/yiisoft/yii/framework/db/CDbMigration.php(53): m150414_124659_add_order_coupon_table->safeUp() #4 /home/kmolchanov/web/runjoy/protected/modules/yupe/components/Migrator.php(249): CDbMigration->up() #5 /home/kmolchanov/web/runjoy/protected/modules/yupe/components/Migrator.php(73): yupe\components\Migrator->migrateUp('coupon', 'm150414_124659_...') #6 /home/kmolchanov/web/runjoy/protected/modules/yupe/components/WebModule.php(887): yupe\components\Migrator->updateToLatest('coupon') #7 /home/kmolchanov/web/runjoy/protected/modules/yupe/components/WebModule.php(800): yupe\components\WebModule->installDB() #8 /home/kmolchanov/web/runjoy/protected/modules/install/controllers/DefaultController.php(934): yupe\components\WebModule->getInstall() #9 [internal function]: DefaultController->actionModuleinstall('coupon') #10 /home/kmolchanov/web/runjoy/vendor/yiisoft/yii/framework/web/actions/CAction.php(109): ReflectionMethod->invokeArgs(Object(DefaultController), Array) #11 /home/kmolchanov/web/runjoy/vendor/yiisoft/yii/framework/web/actions/CInlineAction.php(47): CAction->runWithParamsInternal(Object(DefaultController), Object(ReflectionMethod), Array) #12 /home/kmolchanov/web/runjoy/vendor/yiisoft/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array) #13 /home/kmolchanov/web/runjoy/vendor/yiisoft/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction)) #14 /home/kmolchanov/web/runjoy/vendor/yiisoft/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array) #15 /home/kmolchanov/web/runjoy/vendor/yiisoft/yii/framework/web/CWebApplication.php(282): CController->run('moduleinstall') #16 /home/kmolchanov/web/runjoy/vendor/yiisoft/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('install/default...') #17 /home/kmolchanov/web/runjoy/vendor/yiisoft/yii/framework/base/CApplication.php(184): CWebApplication->processRequest() #18 /home/kmolchanov/web/runjoy/public/index.php(39): CApplication->run() #19 {main}
```
Видимо конфликт версий модулей.
И в целом не ясно как пользоваться стабильной версией и обновляться до новой стабильной используя композер. Это не помешало бы в документации, включая описание обновления структуры базы данных и деплоя на боевой сервер в случае появления новых версий.

**Comment by yupe** [comment]
Ошибку проверим. До стабильной версии, к сожалению, только через композер обновиться не получится. Придется часть труда проделать "ручками". Вообще новые гайды пишутся и будут вот здесь http://guides-v1.yupe-project.ru Про обновление можете почитать вот тут http://guides-v1.yupe-project.ru/update/

**Comment by yupe** [comment]
@sabian проверь, пожауйста, как время будет. Интересует установка на Open Server в двух вариантах: все модули и интернет-магазин.

**Comment by sabian** [comment]
У меня нет Open Server :)

**Comment by yupe** [comment]
Ты ж вроде на винде проверял как-то ? -)

**Comment by sabian** [comment]
Извиняюсь, забыл про виртуальную машину. Вечером проверю обязательно.

**Comment by yupe** [comment]
Пасиб +)
