### ISSUE TITLE
Консольные команды не работают

### ISSUE THREAD

**Issue by loveorigami** [yupe/yupe#2486]
Настройки все стандартные.
Создал свою команду для консоли
```php
class MyimportCommand extends \CConsoleCommand
{
    public function run() {
        echo 111;
    }

}
```
после вызова получаю ошибки
```
Stack trace:
#0 X:\domains\_work\pediatr-24.yii\vendor\yiisoft\yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 X:\domains\_work\pediatr-24.yii\vendor\yiisoft\yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 X:\domains\_work\pediatr-24.yii\vendor\yiisoft\yii\framework\base\CModule.php(394): CDbConnection->init()
#3 X:\domains\_work\pediatr-24.yii\vendor\yiisoft\yii\framework\base\CApplication.php(459): CModule->getComponent('db')
#4 X:\domains\_work\pediatr-24.yii\vendor\yiisoft\yii\framework\db\ar\CActiveRecord.php(637): CApplication->getDb()
#5 X:\domains\_work\pediatr-24.yii\vendor\yiisoft\yii\framework\db\ar\CActiveRecord.php(2386): CActiveRecord->getDbConnection()
#6 X:\domains\_work\pediatr-24.yii\vendor\yiisoft\yii\framework\db\ar\CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Page))
#7 X:\domains\_work\pediatr-24.yii\vendor\yiisoft\yii\framework\db\ar\CActiveRecord.php(212): CActiveRecord->getMetaData()
#8 X:\domains\_work\pediatr-24.yii\protected\modules\page\behaviors\PageBehavior.php(36): CActiveRecord->__call('published', Array)
#9 X:\domains\_work\pediatr-24.yii\protected\modules\page\behaviors\PageBehavior.php(36): Page->published()
#10 X:\domains\_work\pediatr-24.yii\vendor\yiisoft\yii\framework\base\CComponent.php(561): PageBehavior->onBeginRequest(Object(CEvent))
#11 X:\domains\_work\pediatr-24.yii\vendor\yiisoft\yii\framework\base\CApplication.php(212): CComponent->raiseEvent('onBeginRequest', Object(CEvent))
#12 X:\domains\_work\pediatr-24.yii\vendor\yiisoft\yii\framework\base\CApplication.php(183): CApplication->onBeginRequest(Object(CEvent))
#13 X:\domains\_work\pediatr-24.yii\protected\yiic.php(11): CApplication->run()
#14 {main}

``` 

аналогично и при вызове команд из модуля yupe
```
protected\modules\yupe\commands\YupeCommand.php

yiic yupe update_config
```

**Comment by yupe** [comment]
Только что проверил:
b:/var/www/yupe/protected$ php yiic yupe update
The following modules have update for config files: feedback.
Are you sure you want to do this? (yes|no) [no]:yes

Change module "feedback"
Module "feedback" successfully updated!
There is no modules to update migrations.


Все работает =)

**Comment by yupe** [comment]
Какая у вас версия ?

**Comment by loveorigami** [comment]
последняя. Эта же команда выкидывает те же ошибки
![2016-06-02_10-29-09](https://cloud.githubusercontent.com/assets/98164/15736982/0385d4cc-28ac-11e6-9111-2104d9515613.jpg)

**Comment by sabian** [comment]
У вас не настроено соединение с базой данных

**Comment by yupe** [comment]
@sabian неа, не то. Почему при yupe update подтягивается моделька Page ? Такого быть не должно.

**Comment by loveorigami** [comment]
ну а как я в админку попадаю? (см скрин).

**Comment by yupe** [comment]
@loveorigami конфиги консольного приложения правили ?

**Comment by loveorigami** [comment]
вот конфиг console.php
```
<?php
Yii::setPathOfAlias('application', __DIR__ . '/../');
Yii::setPathOfAlias('yupe', __DIR__ . '/../modules/yupe/');
Yii::setPathOfAlias('vendor', __DIR__ . '/../../vendor/');
Yii::setPathOfAlias('themes', __DIR__ . '/../../themes/');

return [
    // У вас этот путь может отличаться. Можно подсмотреть в config/main.php.
    'basePath' => dirname(__DIR__),
    'name' => 'Cron',
    'preload' => ['log'],
    'commandMap' => [
        'migrate' => [
            'class' => 'vendor.yiiext.migrate-command.EMigrateCommand',
            'migrationPath' => 'application.modules.yupe.install.migrations',
            'migrationTable' => '{{migrations}}',
            'applicationModuleName' => 'yupe',
            'migrationSubPath' => 'install.migrations',
            'connectionID' => 'db',
            'templateFile' => 'application.modules.yupe.migrations.migration-template',
        ],
    ],
    'import' => [
        'application.commands.*',
        'application.components.*',
        'application.models.*',
    ],
    'aliases' => [
        'webroot' => dirname(dirname(__DIR__)) . DIRECTORY_SEPARATOR . 'public',
    ],
    // Перенаправляем журнал для cron-а в отдельные файлы
    'components' => [
        'moduleManager' => ['class' => 'yupe\components\ModuleManager'],
        'configManager' => ['class' => 'yupe\components\ConfigManager'],
        // Работа с миграциями, обновление БД модулей
        'migrator' => ['class' => 'yupe\components\Migrator'],
        'themeManager' => [
            'class' => 'CThemeManager',
            'basePath' => dirname(__DIR__) . '/../themes',
            'themeClass' => 'yupe\components\Theme'
        ],
        'request' => [
            'class' => 'yupe\components\HttpRequest',
            'enableCsrfValidation' => true,
            'csrfCookie' => ['httpOnly' => true],
            'csrfTokenName' => 'YUPE_TOKEN',
            'enableCookieValidation' => true,
            // подробнее: http://www.yiiframework.com/doc/guide/1.1/ru/topics.security#sec-4
        ],
        // компонент для отправки почты
        'mail' => [
            'class' => 'yupe\components\Mail',
        ],
        'log' => [
            'class' => 'CLogRouter',
            'routes' => [
                [
                    'class' => 'CFileLogRoute',
                    'logFile' => 'cron.log',
                    'levels' => 'error, warning, info',
                ],
                [
                    'class' => 'CFileLogRoute',
                    'logFile' => 'cron_trace.log',
                    'levels' => 'trace',
                ],
            ],
        ],
        'cache' => [
            'class' => 'CDummyCache',
            'behaviors' => [
                'clear' => [
                    'class' => 'TaggingCacheBehavior',
                ],
            ],
        ],
        // параметры подключения к базе данных, подробнее http://www.yiiframework.ru/doc/guide/ru/database.overview
        'db' => file_exists(__DIR__ . '/db.php') ? require_once __DIR__ . '/db.php' : []
    ],
    'modules' => ['yupe' => ['class' => 'application.modules.yupe.YupeModule', 'cache' => true,],]
];

```

**Comment by loveorigami** [comment]
убирал только 
```
        'application.components.*',
        'application.models.*',
```
чистил кеш, запускал заново - то же самое

**Comment by yupe** [comment]
На версии из dev-ветки повторить не получается.
Проблема вот тут:
```
#11 X:\domains\_work\pediatr-24.yii\vendor\yiisoft\yii\framework\base\CApplication.php(212): CComponent->raiseEvent('onBeginRequest', Object(CEvent))
#12 X:\domains\_work\pediatr-24.yii\vendor\yiisoft\yii\framework\base\CApplication.php(183): CApplication->onBeginRequest(Object(CEvent)
```

Вообще не очень понятно откуда в консольном приложении onBeginRequest

**Comment by yupe** [comment]
Для теста попробуйте в админке отключите модуль Page ?

**Comment by loveorigami** [comment]
на предыдущей версии yupe 0.9.9 (проверил на др. проекте) все работает.
там в модуле page отстутствует PageBehavior

сейчас ... я ручками убрал все из PageBehavior, набрал ```yiic help``` все работает

**Comment by yupe** [comment]
Угу, вопрос теперь в том, почему у вас инициализируется моделька Page

**Comment by loveorigami** [comment]
Вы у себя почистите кеш настроек, запустите на dev ветке, может и у вас ошибка появится.

**Comment by loveorigami** [comment]
у меня что то меняется в консоли только после очистки кеша

**Comment by yupe** [comment]
Все корректно работает. Настройки консольного приложения кешируются в /runtime/cached_settings_console.php можете приложить этот файлик ?

**Comment by sabian** [comment]
У меня не повторяется. Кеши чистил.

**Comment by loveorigami** [comment]
У меня локалка на OpenServer Win 7
```php
<?php return array (
  'basePath' => 'X:\\domains\\_work\\pediatr-24.yii\\protected',
  'name' => 'Cron',
  'preload' => 
  array (
    0 => 'log',
    1 => 'log',
  ),
  'commandMap' => 
  array (
    'migrate' => 
    array (
      'class' => 'vendor.yiiext.migrate-command.EMigrateCommand',
      'migrationPath' => 'application.modules.yupe.install.migrations',
      'migrationTable' => '{{migrations}}',
      'applicationModuleName' => 'yupe',
      'migrationSubPath' => 'install.migrations',
      'connectionID' => 'db',
      'templateFile' => 'application.modules.yupe.migrations.migration-template',
    ),
    'comments-migrate-to-ns' => 
    array (
      'class' => 'application.modules.comment.commands.MigrateToNestedSets',
    ),
    'yupe' => 
    array (
      'class' => 'application.modules.yupe.commands.YupeCommand',
    ),
    'testenv' => 
    array (
      'class' => 'application.modules.yupe.commands.TestEnvCommand',
    ),
  ),
  'import' => 
  array (
    0 => 'application.commands.*',
    1 => 'application.components.*',
    2 => 'application.models.*',
    3 => 'application.modules.callback.CallbackModule',
    4 => 'application.modules.callback.listeners.CallbackTemplateListener',
    5 => 'application.modules.category.models.*',
    6 => 'application.modules.clinica.models.*',
    7 => 'application.modules.clinica.widgets.*',
    8 => 'vendor.yiiext.taggable-behavior.*',
    9 => 'application.modules.comment.models.*',
    10 => 'application.modules.comment.events.*',
    11 => 'application.modules.comment.listeners.*',
    12 => 'application.modules.blog.models.*',
    13 => 'vendor.yiiext.nested-set-behavior.NestedSetBehavior',
    14 => 'application.modules.yupe.YupeModule',
    15 => 'application.modules.image.models.*',
    16 => 'application.modules.notify.listeners.*',
    17 => 'application.modules.page.events.*',
    18 => 'application.modules.page.listeners.*',
    19 => 'application.modules.page.models.*',
    20 => 'application.modules.page.components.*',
    21 => 'application.modules.rbac.listeners.AccessControlListener',
    22 => 'application.modules.blog.listeners.SitemapGeneratorListener',
    23 => 'application.modules.news.listeners.NewsSitemapGeneratorListener',
    24 => 'application.modules.page.listeners.PageSitemapGeneratorListener',
    25 => 'application.modules.store.listeners.StoreSitemapGeneratorListener',
    26 => 'application.modules.user.UserModule',
    27 => 'application.modules.user.models.*',
    28 => 'application.modules.user.forms.*',
    29 => 'application.modules.user.components.*',
    30 => 'application.modules.yupe.components.validators.*',
    31 => 'application.modules.yupe.components.exceptions.*',
    32 => 'application.modules.yupe.extensions.tagcache.*',
    33 => 'application.modules.yupe.helpers.*',
    34 => 'application.modules.yupe.models.*',
    35 => 'application.modules.yupe.widgets.*',
    36 => 'application.modules.yupe.controllers.*',
    37 => 'application.modules.yupe.components.*',
  ),
  'aliases' => 
  array (
    'webroot' => 'X:\\domains\\_work\\pediatr-24.yii\\public',
  ),
  'components' => 
  array (
    'moduleManager' => 
    array (
      'class' => 'application.modules.rbac.components.ModuleManager',
    ),
    'configManager' => 
    array (
      'class' => 'yupe\\components\\ConfigManager',
    ),
    'migrator' => 
    array (
      'class' => 'yupe\\components\\Migrator',
    ),
    'themeManager' => 
    array (
      'class' => 'CThemeManager',
      'basePath' => 'X:\\domains\\_work\\pediatr-24.yii\\protected/../themes',
      'themeClass' => 'yupe\\components\\Theme',
    ),
    'request' => 
    array (
      'class' => 'yupe\\components\\HttpRequest',
      'enableCsrfValidation' => true,
      'csrfCookie' => 
      array (
        'httpOnly' => true,
      ),
      'csrfTokenName' => 'YUPE_TOKEN',
      'enableCookieValidation' => true,
    ),
    'mail' => 
    array (
      'class' => 'yupe\\components\\Mail',
    ),
    'log' => 
    array (
      'class' => 'CLogRouter',
      'routes' => 
      array (
        0 => 
        array (
          'class' => 'CFileLogRoute',
          'logFile' => 'cron.log',
          'levels' => 'error, warning, info',
        ),
        1 => 
        array (
          'class' => 'CFileLogRoute',
          'logFile' => 'cron_trace.log',
          'levels' => 'trace',
        ),
      ),
    ),
    'cache' => 
    array (
      'class' => 'CFileCache',
      'behaviors' => 
      array (
        'clear' => 
        array (
          'class' => 'application.modules.yupe.extensions.tagcache.TaggingCacheBehavior',
        ),
      ),
    ),
    'db' => 
    array (
      'class' => 'CDbConnection',
      'connectionString' => 'mysql:host=localhost;port=3306;dbname=avtonomorg_np24',
      'username' => 'avtonomorg_np24',
      'password' => 'origami2015ped24',
      'emulatePrepare' => true,
      'charset' => 'utf8',
      'enableParamLogging' => 0,
      'enableProfiling' => 0,
      'schemaCachingDuration' => 108000,
      'tablePrefix' => 'mx_',
      'pdoClass' => 'yupe\\extensions\\NestedPDO',
    ),
    'postManager' => 
    array (
      'class' => 'application.modules.blog.components.PostManager',
    ),
    'eventManager' => 
    array (
      'class' => 'yupe\\components\\EventManager',
      'events' => 
      array (
        'sitemap.before.generate' => 
        array (
          0 => 
          array (
            0 => '\\SitemapGeneratorListener',
            1 => 'onGenerate',
          ),
          1 => 
          array (
            0 => '\\ClinicaSitemapGeneratorListener',
            1 => 'onGenerate',
          ),
          2 => 
          array (
            0 => '\\NewsSitemapGeneratorListener',
            1 => 'onGenerate',
          ),
          3 => 
          array (
            0 => '\\PageSitemapGeneratorListener',
            1 => 'onGenerate',
          ),
        ),
        'template.head.end' => 
        array (
          0 => 
          array (
            0 => 'CallbackTemplateListener',
            1 => 'js',
          ),
        ),
        'comment.add.success' => 
        array (
          0 => 
          array (
            0 => 'NewCommentListener',
            1 => 'onSuccessAddComment',
          ),
          1 => 
          array (
            0 => 'NotifyNewCommentListener',
            1 => 'onNewComment',
          ),
        ),
        'comment.before.add' => 
        array (
          0 => 
          array (
            0 => 'NewCommentListener',
            1 => 'onBeforeAddComment',
          ),
        ),
        'comment.after.save' => 
        array (
          0 => 
          array (
            0 => 'NewCommentListener',
            1 => 'onAfterSaveComment',
          ),
        ),
        'comment.after.delete' => 
        array (
          0 => 
          array (
            0 => 'NewCommentListener',
            1 => 'onAfterDeleteComment',
          ),
        ),
        'user.success.activate' => 
        array (
          0 => 
          array (
            0 => 'UserActivationListener',
            1 => 'onUserActivate',
          ),
        ),
        'page.after.save' => 
        array (
          0 => 
          array (
            0 => '\\PageListener',
            1 => 'onAfterSave',
          ),
        ),
        'yupe.backend.controller.init' => 
        array (
          0 => 
          array (
            0 => 'AccessControlListener',
            1 => 'onBackendControllerInit',
          ),
        ),
        'user.success.registration' => 
        array (
          0 => 
          array (
            0 => 'UserManagerListener',
            1 => 'onUserRegistration',
          ),
        ),
        'user.success.password.recovery' => 
        array (
          0 => 
          array (
            0 => 'UserManagerListener',
            1 => 'onPasswordRecovery',
          ),
        ),
        'user.success.activate.password' => 
        array (
          0 => 
          array (
            0 => 'UserManagerListener',
            1 => 'onSuccessActivatePassword',
          ),
        ),
        'user.success.email.confirm' => 
        array (
          0 => 
          array (
            0 => 'UserManagerListener',
            1 => 'onSuccessEmailConfirm',
          ),
        ),
        'user.success.email.change' => 
        array (
          0 => 
          array (
            0 => 'UserManagerListener',
            1 => 'onSuccessEmailChange',
          ),
        ),
      ),
    ),
    'callbackManager' => 
    array (
      'class' => 'application.modules.callback.components.CallbackManager',
    ),
    'commentManager' => 
    array (
      'class' => 'application.modules.comment.components.CommentManager',
    ),
    'feedback' => 
    array (
      'class' => 'application.modules.feedback.components.FeedbackService',
    ),
    'mailMessage' => 
    array (
      'class' => 'application.modules.mail.components.YMailMessage',
    ),
    'authManager' => 
    array (
      'class' => 'CDbAuthManager',
      'connectionID' => 'db',
      'assignmentTable' => '{{user_user_auth_assignment}}',
      'itemChildTable' => '{{user_user_auth_item_child}}',
      'itemTable' => '{{user_user_auth_item}}',
    ),
    'sitemapGenerator' => 
    array (
      'class' => 'application.modules.sitemap.components.SitemapGenerator',
    ),
    'user' => 
    array (
      'class' => 'application.modules.user.components.YWebUser',
      'loginUrl' => 
      array (
        0 => '/user/account/login',
      ),
      'identityCookie' => 
      array (
        'httpOnly' => true,
      ),
    ),
    'userManager' => 
    array (
      'class' => 'application.modules.user.components.UserManager',
      'hasher' => 
      array (
        'class' => 'application.modules.user.components.Hasher',
      ),
      'tokenStorage' => 
      array (
        'class' => 'application.modules.user.components.TokenStorage',
      ),
    ),
    'authenticationManager' => 
    array (
      'class' => 'application.modules.user.components.AuthenticationManager',
    ),
    'notify' => 
    array (
      'class' => 'yupe\\components\\Notify',
      'mail' => 
      array (
        'class' => 'yupe\\components\\Mail',
      ),
    ),
    'thumbnailer' => 
    array (
      'class' => 'yupe\\components\\image\\Thumbnailer',
      'options' => 
      array (
        'jpeg_quality' => 90,
        'png_compression_level' => 8,
      ),
    ),
    'ajax' => 
    array (
      'class' => 'yupe\\components\\AsyncResponse',
    ),
  ),
  'modules' => 
  array (
    'yupe' => 
    array (
      'class' => 'application.modules.yupe.YupeModule',
      'cache' => true,
      'components' => 
      array (
        'bootstrap' => 
        array (
          'class' => 'vendor.clevertech.yii-booster.src.components.Booster',
          'coreCss' => true,
          'responsiveCss' => true,
          'yiiCss' => true,
          'jqueryCss' => true,
          'enableJS' => true,
          'fontAwesomeCss' => true,
          'enableNotifierJS' => false,
        ),
      ),
      'visualEditors' => 
      array (
        'redactor' => 
        array (
          'class' => 'yupe\\widgets\\editors\\Redactor',
        ),
        'ckeditor' => 
        array (
          'class' => 'yupe\\widgets\\editors\\CKEditor',
        ),
        'textarea' => 
        array (
          'class' => 'yupe\\widgets\\editors\\Textarea',
        ),
      ),
    ),
    'blog' => 
    array (
      'class' => 'application.modules.blog.BlogModule',
      'panelWidgets' => 
      array (
        'application.modules.blog.widgets.PanelStatWidget' => 
        array (
          'limit' => 5,
        ),
      ),
    ),
    'callback' => 
    array (
      'class' => 'application.modules.callback.CallbackModule',
    ),
    'category' => 
    array (
      'class' => 'application.modules.category.CategoryModule',
    ),
    'clinica' => 
    array (
      'class' => 'application.modules.clinica.ClinicaModule',
    ),
    'comment' => 
    array (
      'class' => 'application.modules.comment.CommentModule',
      'panelWidgets' => 
      array (
        'application.modules.comment.widgets.PanelCommentStatWidget' => 
        array (
          'limit' => 5,
        ),
      ),
      'visualEditors' => 
      array (
        'redactor' => 
        array (
          'class' => 'comment\\widgets\\editors\\CommentRedactor',
        ),
        'textarea' => 
        array (
          'class' => 'yupe\\widgets\\editors\\Textarea',
        ),
      ),
    ),
    'contentblock' => 
    array (
      'class' => 'application.modules.contentblock.ContentBlockModule',
    ),
    'feedback' => 
    array (
      'class' => 'application.modules.feedback.FeedbackModule',
      'panelWidgets' => 
      array (
        'application.modules.feedback.widgets.PanelFeedbackStatWidget' => 
        array (
          'limit' => 5,
        ),
      ),
    ),
    'gallery' => 
    array (
      'class' => 'application.modules.gallery.GalleryModule',
    ),
    'image' => 
    array (
      'class' => 'application.modules.image.ImageModule',
    ),
    'mail' => 
    array (
      'class' => 'application.modules.mail.MailModule',
    ),
    'menu' => 
    array (
      'class' => 'application.modules.menu.MenuModule',
    ),
    'news' => 
    array (
      'class' => 'application.modules.news.NewsModule',
    ),
    'notify' => 
    array (
      'class' => 'application.modules.notify.NotifyModule',
    ),
    'page' => 
    array (
      'class' => 'application.modules.page.PageModule',
    ),
    'rbac' => 
    array (
      'class' => 'application.modules.rbac.RbacModule',
    ),
    'sitemap' => 
    array (
      'class' => 'application.modules.sitemap.SitemapModule',
    ),
    'user' => 
    array (
      'class' => 'application.modules.user.UserModule',
      'panelWidgets' => 
      array (
        'application.modules.user.widgets.PanelUserStatWidget' => 
        array (
          'limit' => 5,
        ),
      ),
      'documentRoot' => '',
      'avatarsDir' => 'avatars',
      'notifyEmailFrom' => 'test@test.ru',
    ),
  ),
  'behaviors' => 
  array (
    'page' => 
    array (
      'class' => 'application.modules.page.behaviors.PageBehavior',
    ),
  ),
);
```

**Comment by loveorigami** [comment]
разница с другим рабочим в том, что тут добавился
```php
  'behaviors' => 
  array (
    'page' => 
    array (
      'class' => 'application.modules.page.behaviors.PageBehavior',
    ),
  ),
```

**Comment by yupe** [comment]
У меня эта запись тоже есть и с ней все работает корректно.

**Comment by loveorigami** [comment]
пишу по ходу.
удалил cached_settings_console. Набрал yiic help. Файл создался заново. Все работает.

**Comment by yupe** [comment]
Значит у вас настройки были закешированы какие-то старые. Сейчас все корректно ?

**Comment by sabian** [comment]
Ну вот, а говорите кеш чистили

**Comment by loveorigami** [comment]
кеш чистил из админки... сейчас смотрю - в runtime/cache он у меня остается.
т.е. из админки не чистится, получается...

**Comment by sabian** [comment]
Вы не подтвердили работоспособность. С включенным модулем page теперь у вас работают консольные команды?

**Comment by yupe** [comment]
@loveorigami кеш настроек консольного приложения чистится только ручками. Это именно кеш настроект, а не кеш всего приложения. Кеш настроек веб-приложения можно очистить из админки.

**Comment by loveorigami** [comment]
Да, теперь все работает... ). Спасибо за ликбез.
